### PR TITLE
fix indentation typo (tab/spaces -> tabs)

### PR DESCRIPTION
**Pull request by loloicci**
Fix typo of indentation in `templates/module/types/key.go.tmpl`

### CODE REVIEW

**Comment by marbar3778** [comment]
thank you for the contribution. we have since depreacted this repo in favor of https://github.com/tendermint/starport/.

**Comment by loloicci** [comment]
Thank you for replying!
I didn't know that. Would you write this information to README?

However, this tool is used in the Nameservice section in cosmos-sdk-tutorial (https://tutorials.cosmos.network/nameservice/tutorial/00-intro.html , https://tutorials.cosmos.network/nameservice/tutorial/04-key.html).
If `querierer` is a typo, fixing this may helps the tutorial readers.

And if this is a typo, I'll make a PR to starport if the `fix typo (querierer -> querier)` commit is collect fix.
Is it ok?

**Comment by marbar3778** [comment]
we can merge this PR and once I get a chance I will go rewrite the tutorials.

**Comment by loloicci** [comment]
Thanks, I'm glad I can help the sdk-tutorial!

**Pull request merged**
