### PR TITLE
v0.38.0 update

### PR DESCRIPTION
**Pull request by okwme**
- [x] update app command
- [x] update module command

### CODE REVIEW

**Comment by marbar3778** [comment]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia1.giphy.com%2Fmedia%2Fl0HlFKETqoU9z44RG%2Fgiphy.gif&token=giddy" data-gitmeme-token="giddy"></a>

**Comment by okwme** [comment]
Discussing it with @marbar3778 we realized that we shouldn't update the Modules repo until v0.38 is shipped as many features of a module are finalized.

**Comment by marbar3778** [comment]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia0.giphy.com%2Fmedia%2Fl2YWxte7sJB2XuE8M%2Fgiphy.gif&token=continue" data-gitmeme-token="continue"></a>

**Comment by marbar3778** [comment]
this is done with app and module @okwme. the tutorials are not fixed tho. I am for removing them for now in favor of the clone command being used for it.

**Comment by okwme** [comment]
module CI fails locally when used like:
```bash
GL_DEBUG=linters_output GOPACKAGESPRINTGOLISTERRORS=1 golangci-lint -v run
```
(I added the debug flags because I was previously getting an error based on a bad go.sum package caused by leaving `"github.com/marbar3778/nameservice/app"` within the client templates)

Without the go.sum errors it can also be run like:
```bash
golangci-lint run
```
The results are:
```bash
> golangci-lint run         
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/home/billyrennekamp/GitHub.com/cosmos/foobar/x/foo/internal/types/errors.go:5:2: "github.com/cosmos/cosmos-sdk/types/errors" imported but not used as sdkerrors /home/billyrennekamp/GitHub.com/cosmos/foobar/x/foo/internal/types/msg.go:5:2: "github.com/cosmos/cosmos-sdk/types/errors" imported but not used as sdkerrors /home/billyrennekamp/GitHub.com/cosmos/foobar/x/foo/internal/types/msg.go:4:2: "github.com/cosmos/cosmos-sdk/types" imported but not used as sdk] 
WARN [runner] Can't run linter goanalysis_metalinter: assign: failed prerequisites: inspect@github.com/cosmos/foobar/x/foo/internal/types 
ERRO Running error: assign: failed prerequisites: inspect@github.com/cosmos/foobar/x/foo/internal/types 
```

This is the correct output because the code contains errors. However the CI on the repo does not report these errors and I'm not sure why. It uses a docker instance and I don't see any real output that seems to be related to linting the project...

**Comment by okwme** [comment]
Could still merge this issue as making the default scaffold compile is another open issue which could be handled by another PR...

**Comment by okwme** [comment]
CI linter is running but not doing anything : (

**Comment by marbar3778** [comment]
i think its linting the repo and not the generated code.

**Comment by marbar3778** [comment]
we should add expected keepers here

**Pull request merged**
